name: deploy order

on:
  push:
    branches:
      - main 


jobs:
  
  # job name
  build-and-deploy:
    
    # runner
    runs-on: ubuntu-latest

    # https://docs.github.com/ko/actions
    steps:
      - name: checkout github
        uses: actions/checkout@v2