name: deploy order

on:
  push:
    branches:
      - main 


jobs:
  
  # job name
  build-and-deploy:
    
    # runner
    runs-on: ubuntu-latest

    # https://docs.github.com/ko/actions
    steps:
      - name: checkout github
        uses: actions/checkout@v2

      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.34.1"

      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_KEY}}
          aws-secret-access-key: ${{secrets.AWS_SECRET}}
          aws-region: us-west-1

      - name: aws eks cluster update
        run: aws eks update-kubeconfig --region us-west-1 --name lgcns-seoyoomi-cluster

      - name: aws ecr login
        uses: aws-actions/amazon-ecr-login@v1

      # infra 구축   
      - name: deploy infra
        run: |
          kubectl apply -f k8s/msa_ingress.yml
          kubectl apply -f k8s/msa-kafka.yml
          kubectl apply -f k8s/msa-redis.yml
          kubectl apply -f k8s/msa-zookeeper.yml